### ISSUE TITLE
in-browser dataviz plotter fails to load some hlog files

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HdrHistogramJS#1] opened 2017-03-09 01:35 UTC
I've been using the dataviz plotter at https://alexvictoor.github.io/HdrHistogramJSDemo/logparser.html to plot jHiccup log files, and its' worked pretty well as a quick alternative to HistogramLogAnalyzer (https://github.com/HdrHistogram/HistogramLogAnalyzer). But someone just game me a jHiccup log file (attached) that loads fine in HistogramLogAnalyzer but doesn't plot with the in-broswer JS plotter. Since it's a reproducer file, I figured I'd attach it here and open an issue...
[repoducer.zip](https://github.com/HdrHistogram/HdrHistogramJS/files/829474/repoducer.zip)

**Comment by alexvictoor** [comment] 2017-03-22 23:10
Hello
Sorry for this late answer (I am quite busy preparing my devoxx france talk on hdrhistogram actually ;) )
I guess the problem is that currently only log format version 1.2 is supported in HDRHistogramJS.
If you think that it is important to handle oldest formats, I can add that to my backlog, this will not be an heavy task.

**Comment by giltene** [comment] 2017-03-22 23:33
Hmm. I haven't noticed that jHiccup 2.0.6 still used an older HdrHistogram versions and therefore generates logs in version 1.1 format. I'll update 2.0.7 to use the latest in any case. 
Up to you on whether you want to support 1.1. I think it's fine to only support 1.2+, as older versions will wash out over time.

**Comment by alexvictoor** [comment] 2017-10-24 20:51
Only 1.2+ supported. I close this issue. If someone needs support for an older format, do not hesitate to raise an issue

**Closed by alexvictoor** 2017-10-24 20:51 UTC
